# Generated by Django 2.2.5 on 2019-09-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190917_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='subs',
            name='price',
            field=models.FloatField(default=6.5),
        ),
        migrations.AlterField(
            model_name='subs',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('L', 'Large')], default='S', max_length=1),
        ),
    ]
