# Generated by Django 2.2.5 on 2019-09-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_shoppingcart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShoppingCart',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='total_price',
            new_name='order_price',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='item',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='price_item',
        ),
        migrations.AddField(
            model_name='orders',
            name='order_description',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
